services:
  discovery-server:
    build: ./infra/discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://localhost:8761/eureka/apps" ]
      interval: 5s
      timeout: 5s
      retries: 10

  config-server:
    build: ./infra/config-server
    container_name: config-server
    depends_on:
      discovery-server:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=/config


  stats-db:
    image: postgres:16.1
    container_name: stats-db
    environment:
      - POSTGRES_DB=statsdb
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
    volumes:
      - ./volumes/stats-db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U dbuser -d statsdb" ]
      interval: 5s
      timeout: 5s
      retries: 5

  stats-server:
    build:
      context: ./stats/stats-server
      dockerfile: Dockerfile
    container_name: stats-server
    depends_on:
      stats-db:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
      config-server:
        condition: service_started
    environment:
      - SPRING_CLOUD_CONFIG_DISCOVERY_ENABLED=true
      - SPRING_CLOUD_CONFIG_DISCOVERY_SERVICE_ID=config-server
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statsdb
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/

  ewm-db:
    image: postgres:16.1
    container_name: ewm-db
    environment:
      - POSTGRES_DB=ewmdb
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
    volumes:
      - ./volumes/ewm-db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U dbuser -d ewmdb" ]
      interval: 5s
      timeout: 5s
      retries: 5

  main-service:
    build:
      context: ./core/main-service
      dockerfile: Dockerfile
    container_name: main-service
    depends_on:
      stats-server:
        condition: service_started
      ewm-db:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
      config-server:
        condition: service_started
    environment:
      - SPRING_CLOUD_CONFIG_DISCOVERY_ENABLED=true
      - SPRING_CLOUD_CONFIG_DISCOVERY_SERVICE_ID=config-server
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewmdb


  gateway-server:
    build:
      context: ./infra/gateway-server
      dockerfile: Dockerfile
    container_name: gateway-server
    ports:
      - "8080:8080"
    depends_on:
      discovery-server:
        condition: service_healthy
      config-server:
        condition: service_started
    environment:
      - SPRING_CLOUD_CONFIG_DISCOVERY_ENABLED=true
      - SPRING_CLOUD_CONFIG_DISCOVERY_SERVICE_ID=config-server
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka-grad
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  kafka-setup:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka-setup-grad
    depends_on:
      - kafka
    command:
      - /bin/bash
      - -c
      - |
        while ! kafka-topics --bootstrap-server kafka:29092 --list 2>/dev/null; do
          sleep 2
        done
        echo "Kafka запущена! Создаю топики..."
        kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic stats.user-actions.v1 --partitions 1 --replication-factor 1
        kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic stats.events-similarity.v1 --partitions 1 --replication-factor 1
        echo "Успех! Топики созданы."