
CREATE TABLE IF NOT EXISTS events_similarity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_a_id BIGINT NOT NULL,
    event_b_id BIGINT NOT NULL,
    score DOUBLE PRECISION NOT NULL,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_events_similarity UNIQUE (event_a_id, event_b_id)
);

CREATE TABLE IF NOT EXISTS user_actions_history (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     user_id BIGINT NOT NULL,
     event_id BIGINT NOT NULL,
     action_score DOUBLE PRECISION NOT NULL,
     created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
     CONSTRAINT uq_user_actions UNIQUE (user_id, event_id)
);